<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rus_slam_navigation</name>
  <version>0.1.0</version>
  <description>Навигационный стек: slam_toolbox (картографирование), Nav2 (планирование и ведение), AMCL (локализация)</description>
  <maintainer email="team@rus-slam.local">RUS SLAM Team</maintainer>
  <license>MIT</license>

  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>navigation2</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
